### ISSUE TITLE
Reject promise in middleware

### ISSUE THREAD

**Issue by wideving** [vadymmarkov/Malibu#111]
I'm doing authentication in middleware and when authentication fails I want to reject the promise with a custom error object. Where do I catch this error object? I have added validate(), done(), fail() and always handlers but none of them seem to be called. Have I misunderstood how reject works?

**Comment by wideving** [comment]
I will add an example of what I try to do

fun getAuth() {
    networking.request(.getAuth)
    .validate()
    .done { response in
      //None of these handlers gets called
    }
    .fail { error in
        
    }
    .always { result in 
      
    }
}

networking.middleware = { promise in 
  promise.reject(NetworkError(code: 999, message: "error..")
}

**Comment by vadymmarkov** [comment]
Hi @wideving! I don't think it's a problem with `reject` itself, there's probably something else. Do you keep a reference to your `Networking` instance so it's not deallocated?

**Comment by wideving** [comment]
Hello @vadymmarkov, thank you for a quick response 👍 I don't think there is a problem with deallocation since the request goes through if I resolve instead of reject. I have no problem with your library other then when i reject in middleware nothing happens. All other requests and functionality is working fine.

Here is the code for how i create an instance of networking, its stored as a reference in appdelegate. The networking object is then injected to a viewmodel and called from there 

`func createApi(unrestrictedApi: Networking<UnrestrictedApi>,
                 session: Session) -> Networking<RestrictedApi> {
    
    let api = Networking<RestrictedApi>()
    api.middleware = { promise in
      if !session.shouldRefreshToken {
        api.authenticate(authorizationHeader: session.authorizationToken)
        promise.resolve(Void())
        return
      }
      
      unrestrictedApi.request(.refresh(phoneNumber: session.phoneNumber))
        .validate()
        .toData()
        .then({response -> String in
          return try JSONDecoder().decode(Authorization.self, from: response).token
        })
        .done({ token in
          guard
            let decryptedToken = CipherUtility.decrypt(encryptedString: token)
          else {
            promise.reject(NetworkError.noDataInResponse)
            return
          }
          
          session.setAuthorizationToken(token: decryptedToken)
          api.authenticate(authorizationHeader: session.authorizationToken)
          promise.resolve(Void())
        })
        .fail({ error in
          let message = NetworkErrorParser.parse(error: error)
          print("error message: \(message)")
          promise.reject(NetworkError.noDataInResponse)
        })
      }

    return api
  }`

UnrestrictedApi and RestrictedApi is stored like this in appdelegate

`private let unrestrictedApi = Networking<UnrestrictedApi>()
  private lazy var restrictedApi: Networking<RestrictedApi> = {
    ApiGenerator().createApi(unrestrictedApi: unrestrictedApi,
                             session: UserAccountSession())
  }()`

Do you spot anything weird?

**Comment by vadymmarkov** [comment]
@wideving You're right, I found a bug in implementation with promise not being rejected when middleware fails. It should be fixed in https://github.com/vadymmarkov/Malibu/pull/112. Please test it on master branch and if it works as expected I'll make a new release.

**Comment by wideving** [comment]
I did a pod update with pod 'Malibu', :git => 'https://github.com/vadymmarkov/Malibu.git', :commit => 'b2afba1' to confirm that issue is solved and everything now works as expected with rejections coming through middleware. Thank you.
