### ISSUE TITLE
SSL Pinning

### ISSUE THREAD

**Issue by dev4jam** [vadymmarkov/Malibu#95]
What's the right way of setting URLCredentials for "session.configuration.urlCredentialStorage?.defaultCredential" in ssl pinning code? Who should be responsible for this part?

**Comment by vadymmarkov** [comment]
It's possible to create `Networking` with custom `URLSessionConfiguration ` https://github.com/hyperoslo/Malibu/blob/master/Sources/Request/SessionConfiguration.swift#L7
